server:
  port: 80
  session:
    timeout: 1800   #session过期时间,springboot默认不能小于1min，源码位置:TomcatEmbeddedServletContainerFactory.getSessionTimeoutInMinutes()
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_demo?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 815211859

  # 所有session的东西都存入redis并进行管理，过期时间与server.session.timeout一致
  session:
    store-type: redis

  redis:
    host: 127.0.0.1
    timeout: 5000        #连接超时时间（毫秒）
    pool:
      max-active: 1000   # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1       # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10       # 连接池中的最大空闲连接
      min-idle: 2        # 连接池中的最小空闲连接

mapper:
  identity: MYSQL
  not-empty: false
  mappers: com.lee.utils.MyMapper

mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com:
      lee:
        mapper: debug

# 自定义配置
security:
  browser:
    loginPage: /login-test.html
    signUpUrl: /signUp-demo.html
  code:
    image:
      width: 67
      height: 23
      length: 4
      expireIn: 60
  social:
    filterProcessesUrl: /socialLogin
    qq:
      app-id: wxd99431bbff8305a0
      app-secret: 60f78681d063590a469f1b297feff3c4
      providerId: callback.do
    weixin:
      app-id: wxd99431bbff8305a0
      app-secret: 60f78681d063590a469f1b297feff3c4
      providerId: weixin
